# Generated by Django 5.0.7 on 2024-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
